# 공통 설정 (모든 프로필에 적용됨)
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  session:
    store-type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
            redirect-uri: ${GITHUB_REDIRECT_URI}
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login

  jwt:
    secret-key: ${JWT_SECRET_KEY}
#    access-token-exp: ${JWT_ACCESS_TOKEN_EXP}
#    refresh-token-exp: ${JWT_REFRESH_TOKEN_EXP}

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT}

github:
  token: ${GITHUB_TOKEN}

---

# dev 프로필 전용 설정
spring:
  config:
    activate:
      on-profile: dev
    import: optional:classpath:conal-back-secret/application-dev.properties

---

# prod 프로필 전용 설정
spring:
  config:
    activate:
      on-profile: prod
    import: optional:classpath:conal-back-secret/application-prod.properties
