# 공통 설정 (모든 프로필에 적용됨)
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

github:
  token: ${GITHUB_TOKEN}
---

# dev 프로필 전용 설정
spring:
  config:
    activate:
      on-profile: dev
    import: optional:classpath:conal-back-secret/application-dev.properties

---

# prod 프로필 전용 설정
spring:
  config:
    activate:
      on-profile: prod
    import: optional:classpath:conal-back-secret/application-prod.properties
